a = float(input("ingese e valor de a"))
b = float(input("ingese e valor de b"))
c = float(input("ingese e valor de c"))
x = (-b-(b**2-4*a*c)**0.5)/(2*a)
x2 = (-b+(b**2-4*a*c)**0.5)/(2*a)
print (x)
print(x2)